server:
  # @dev `local`, `production`
  environment: "local"
  # @note `- port:"3010"` becomes a list in yaml.
  port: "3010"
  database:
    main: "sd_app.db"
    test: "sd_app.test.db"
  decimals:
    ethereum: "1e18"
    usdt: "1e6"
    usdc: "1e6"
    usds: "1e18"
    dai: "1e18"
    pyusd: "1e6"
  contracts:
    mainnet:
      usdt: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      usdc: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      usds: "0xDC035D45D973e3EC169D2276dDab16f1E407384F"
      dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
      pyusd: "0x6c3ea9036406852006290770bedfcaba0e23a0e8"
  domains:
    tradingview: "www.tradingview.com"
    metamask: "metamask.io"
  cron:
    expression:
      default: "0 0 * * * *"
      every1sec: "*/1 * * * * *"
      every1min: "1 * * * * *"
      every30min: "30 * * * * *"
