basePath: /
info:
  contact: {}
  description: SignalDash backend API documentation
  title: SignalDash API
  version: "1.0"
paths:
  /api/health:
    get:
      description: Get server health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Show the health status
      tags:
      - api
  /api/indicator:
    get:
      description: dummy test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: dummy test
      tags:
      - api
swagger: "2.0"
